services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - my-network

  php:
    container_name: php-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports: 
      - "80:80"
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laminas
      MYSQL_USER: rui
      MYSQL_PASSWORD: rui123
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - egoichallenge_db_data:/var/lib/mysql

  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    build: artemis/
    ports:
      - 8161:8161
      # JMX Exporter
      - 9404:9404
      # Netty
      - 9876:9876
      # Port for CORE,MQTT,AMQP,HORNETQ,STOMP,OPENWIRE
      - 61616:61616
      # Port for HORNETQ,STOMP
      - 5445:5445
      # Port for AMQP
      - 5672:5672
      # Port for MQTT
      - 1883:1883
      #Port for STOMP
      - 61613:61613
    volumes:
      - activemq-data:/var/lib/activemq/data
    environment:
      - ACTIVEMQ_USER=artemis
      - ACTIVEMQ_PASSWORD=artemis
      - ANONYMOUS_LOGIN=true
    networks:
      - my-network

volumes:
  egoichallenge_db_data:
  activemq-data:

networks:
  my-network:
    driver: bridge
